version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-safequake
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - safequake-db-data:/var/lib/postgresql/data
    networks:
      - safequake-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  safequake-api:
    build: .
    container_name: safequake-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - safequake-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/swagger-ui/index.html"]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  safequake-db-data:

networks:
  safequake-net:
    driver: bridge
